version: "3"
services:
  bogobot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "2137:2137"
    restart: always
    volumes:
      - ./src:/app/src
